### PR TITLE
 A PCB design for N2 final launch

### PR DESCRIPTION
**Pull request by ianmuchyri**
Look at the PCB design and let me know if there are any issues. I've made a couple of changes in the PCB design where we have a single PCB

### CODE REVIEW

**Review by kimanimichael — CHANGES_REQUESTED** [review]
Show and label ESP32CAM power clearly.

Connectors H3 and H4 can be broken down into 2 position JST instead of 5 as I don't think they are meant to be used together.

Increase copper area clearance for easier etching. Also creating DRC errors.

Add mounting holes at the corners. I'm thinking M3. Avionics bay design will allow screwing of the PCB to it.

There's a weird net appearing in the DRC(SQW). Remove it. Around the SD MISO pin.

Run DRC as I am getting errors on my side.

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
Add changes

**Comment by ianmuchyri** [comment]
the changes I've made

- showed and labeled the esp cam power
- broke down the H2 connectors to two-wire which will be suitable for the two-wire JST
- increased the copper clearance to 0.8mm from 0.256mm
- added the mounting holes
-

**Comment by kimanimichael** [comment]
We need to figure out why the ESP was frying on this PCB.

**Comment by rodneyosodo** [comment]
@Mike-Kimani and @ianmuchyri  why do we have `PCB1`, `PCB2`, `PCB3` and `N2 Final PCB` on this branch?
This is github it will version itself based on commits. No need to do different version. Just stick to one.

**Comment by kimanimichael** [comment]
> @Mike-Kimani and @ianmuchyri why do we have `PCB1`, `PCB2`, `PCB3` and `N2 Final PCB` on this branch? This is github it will version itself based on commits. No need to do different version. Just stick to one.

The reason is because there were different PCB specs we were working on concurrently at the time. If anything, they should have been on completely different branches never to be merged. However, we have abandoned one of them and this issue should be resolved when I review and merge the pull request by @ianmuchyri.

**Comment by kimanimichael** [comment]
The schematic and PCB lgtm. Just a few semantics on the schematic. The +11V8 net is not consistently represented in the CONNECTORS and EJECTION sections. Make it's representation in the EJECTION section to be power symbols too. Also ensure all power symbols face upwards.

Screenshot from 2022-10-04 08-56-12

**Comment by ianmuchyri** [comment]
> @Mike-Kimani and @ianmuchyri why do we have `PCB1`, `PCB2`, `PCB3` and `N2 Final PCB` on this branch? This is github it will version itself based on commits. No need to do different version. Just stick to one.

The new Pull request only has one PCB model. The others had issues so I removed them from the repository. Furthermore, the PCB1, PCB2, and PCB3 were for the decoupled iteration of the PCB and hence are no longer being used.

**Comment by ianmuchyri** [comment]
> The schematic and PCB lgtm. Just a few semantics on the schematic. The +11V8 net is not consistently represented in the CONNECTORS and EJECTION sections. Make it's representation in the EJECTION section to be power symbols too. Also ensure all power symbols face upwards.
> 
> Screenshot from 2022-10-04 08-56-12

I have made the necessary changes, check it out and let me know if anything else requires to be altered.

**Review by kimanimichael — APPROVED** [review]

**Comment by kimanimichael** [comment]
> > The schematic and PCB lgtm. Just a few semantics on the schematic. The +11V8 net is not consistently represented in the CONNECTORS and EJECTION sections. Make it's representation in the EJECTION section to be power symbols too. Also ensure all power symbols face upwards.
> > Screenshot from 2022-10-04 08-56-12
> 
> I have made the necessary changes, check it out and let me know if anything else requires to be altered.

Cool.

**Pull request merged**
